"""empty message

Revision ID: 12a74976df35
Revises: 
Create Date: 2021-04-07 10:20:44.049077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a74976df35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_title', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    # ### end Alembic commands ###
