"""create Link timestamp

Revision ID: 21a10dc65fe9
Revises: 931cd9a985ea
Create Date: 2021-04-06 15:43:59.350005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a10dc65fe9'
down_revision = '931cd9a985ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('link_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_link_link_timestamp'), 'link', ['link_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_link_timestamp'), table_name='link')
    op.drop_column('link', 'link_timestamp')
    # ### end Alembic commands ###
