"""更新models

Revision ID: 417ec121bb60
Revises: 12a74976df35
Create Date: 2021-04-07 15:29:01.837257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417ec121bb60'
down_revision = '12a74976df35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=20), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['category_id'])
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
