"""Post add timestamp

Revision ID: 931cd9a985ea
Revises: 33fb92712ed5
Create Date: 2021-04-06 14:19:01.497952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931cd9a985ea'
down_revision = '33fb92712ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
