"""author add nickname、like

Revision ID: d95fed10405b
Revises: 
Create Date: 2021-03-31 10:02:56.294614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95fed10405b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('like', sa.String(length=20), nullable=True))
    op.add_column('author', sa.Column('nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'nickname')
    op.drop_column('author', 'like')
    # ### end Alembic commands ###
